### ISSUE TITLE
Password reset page does not give feedback

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/Food-for-Good#73]
The password reset page needs to give the user feedback for success and errors in the same fashion as on the signup page.  It should

- Indicate if the new passwords do not match
- disable the submit button if any fields are empty or if the new passwords do not match.
- If the server returns an error it should display the error
- If the server returns success it should display a success message and clear all the form fields

**Comment by joshuahenson** [comment]
I can help with this one.
